Replace exports for Node.js

diff --git a/.github/workflows/release-packages.yml b/.github/workflows/release-packages.yml
--- a/.github/workflows/release-packages.yml
+++ b/.github/workflows/release-packages.yml
@@ -66,14 +66,6 @@ jobs:
 
               cd $dir
 
-              # Build and publish to npm if package.json exists
-              if [ -f "package.json" ]; then
-                echo "Building and publishing $dir to npm..."
-                pnpm install
-                pnpm run build:npm
-                pnpm run publish:npm || echo "npm publish failed for $dir"
-              fi
-
               pnpm run prepare:jsr
 
               # Publish to JSR if jsr.json exists
@@ -82,10 +74,18 @@ jobs:
                 deno publish || echo "JSR publish failed for $dir"
               fi
 
+              # Build and publish to npm if package.json exists
+              if [ -f "package.json" ]; then
+                echo "Building and publishing $dir to npm..."
+                pnpm install
+                pnpm run build:npm
+                # Use the JS Module file as export instead of the TypeScript file
+                sed -i 's/\".\/mod.ts\"/\".\/dist\/mod.mjs\"/g' "package.json"
+                pnpm run publish:npm || echo "npm publish failed for $dir"
+              fi
+
               cd - > /dev/null
             else
               echo "Skipping $dir"
             fi
           done
-
-    
